### ISSUE TITLE
Interest in parsers for other languages and libraries?

### ISSUE THREAD

**Issue by hilts-vaughan** [renatopp/behavior3js#17]
Your editor is one of the only open-source available opens and I think it could be great for others of us writing in other languages (in my case, C#)

Are you open to pull requests for parsers or is this staying strictly JS?

**Comment by renatopp** [comment]
Hi @hilts-vaughan, surely would be great port of b3 to other languages. However I inclined to keep this repository exclusively to javascript in order to keep the maintenance easy and simple.

In this way, we can also have multiple versions of the language. 

I myself will publish soon a version of b3 in python, so feel free to create ports of b3 to other languages. I will link all these ports in the README and in the site.

**Comment by hilts-vaughan** [comment]
Great. I've begun working on a parser in C# for the format.

You can probably expect a few comments on the editor side of things, as
well. Some things I'm interested in adding is having project wide custom
nodes, after project support is added rather than per file.

Great editor and library. Thanks!

**Comment by renatopp** [comment]
Nice, keep me updated of it.

Currently, I'm updating the editor to include projects and multiple trees. I also expect to include a feature to export trees directly to code not only as JSON. The current state of the editor can be found here: http://behavior3js.guineashots.com/editor/dev/

For the next two weeks I'll be working on a [different project](creatine.guineashots.com) of mine, after that I'll have another iteration over the editor and I hope to finish these new features.

I'm closing this question, feel free to comment here or reopen if necessary.
