### ISSUE TITLE
Async Nodes / Actions returning Promises / Composites handling Promises

### ISSUE THREAD

**Issue by FunkMonkey** [renatopp/behavior3js#4]
It would be nice, if there was a set of asynchronous nodes that are able to handle JS Promises, so that Actions can perform asynchronous operations. Thus there also need to be Composites that can deal with these asynchronous Actions.

What do you think?

**Comment by renatopp** [comment]
My first thought on this was completely different of what @FunkMonkey wanted.

What you want is a completely different implementation of what we have now. Behavior3 follows a data-driven architecture while what you want is most similar to event-drive BTs. I don't see any simple way to make the two architectures work together.

The design, problems and decisions in an event-drive bt is completely different from what we have here, so if you really want to implement this system, I don't recommend a fork of the project, but starting a new one from scratch.

If your only concern is about frequent tick of the tree, I don't see any problem except if you are using it in a CPU-intensive application or low-resource devices, which I don't believe, otherwise you would be using C/C++.

I'm closing this issue, fell free to continue the discussion or open it again if needed.

**Comment by FunkMonkey** [comment]
OK, back from vacation and I had some time thinking and creating a prototypical implementation of what I believe is a good compromise.

The basic idea is to have an asynchronous decorator (currently poorly called `AsyncRunner`) that bridges the synchronous and the asynchronous world. This decorator can have an asynchronous child node, which is basically a node, whose `tick` function returns a promise that resolves or rejects with a status (like `b3.SUCCESS`, etc.). This decorator basically works similar to what @grifdail proposed, returning `b3.RUNNING` until the promise is resolved or rejected. 

The child of the asynchronous decorator can be the root of a whole asynchronous tree - I already provided `AsyncSequence` and `AsyncPriority`. Due to the `AsyncRunner` this subtree is not ticked per frame anymore - a tick in the asynchronous subtree takes the time it needs to resolve or reject the promises it consists of. Thus the asynchronous subtree logically behaves like a synchronous tree that spans over time (which is the mere reason I wanted to implement this).

All in all this means that in contrast to my previous proposal the tree itself is ticked continuously and not just on special events, but the asynchronous sub tree is not ticked all the time anymore. 

Some technical remarks:
- `BaseNode.js` is the only file that was touched, but only for adding 2 functions that I simply wanted to be inherited
- I added `_asyncExecute` to `BaseNode` as the equivalent to the synchronous `_execute` - it handles `tick` functions that return promises
- asynchronous nodes have a property `isAsync` and their `_execute` function was overwritten to throw an exception to prevent an asynchronous node from being ticked by a synchronous one (except `AsyncRunner`)
- didn't test it yet, but the asynchronous sub tree should be able to mix synchronous and asynchronous nodes as long as a synchronous node does not tick an asynchronous node

My only concern right now: 
- a `Tick`-object passed to an asynchronous subtree lives longer then usual and may be used in nodes even after new ticks have already been created, meaning that `_nodeCount` and `_openNodes` are still altered after the tree uses them in the main `tick` function to close open nodes
- Question: Why is it necessary that the tree itself closes nodes that are still opened?

Here is the code: [async-tree](https://github.com/FunkMonkey/behavior3js/compare/async-tree)

Do you think this would fit into this project or do you see it more as an extension that should be maintained separately?

**Comment by renatopp** [comment]
Hi @FunkMonkey

I don't see any need to have any other asynchronous node but an "AsyncAction", which execute some given function (like your AsyncRunner). By returning RUNNING, all other nodes will handle it normally. 

Given your situation, I think you could implement one of the following options:

- implementing an event-driven tree by rewriting the `BehaviorTree.tick` function e adding some other methods to support it.

- by ticking the current tree structure when an event occurs. You know that an event occurs because your async action resolved a promise. This async node could set a global flag or something like that to tell the main thread to tick the tree.

Either way, it would be very distant from our core system, so I recommend you to maintain a forked repository of b3js with your async mod.

IMHO, your going with a bad design with your current implementation. You are mixing two different concepts and opting for a non-parsimonious solution.

---

Some considerations about your code:

- Never, in any circumstance, save variables inside the node objects. Instead, use the blackboard. Suppose you want to use the same tree with different agents; by saving variables in the node, you couldn't do that.

- Letting Tick objects living more than one single tick is evil. A tick holds information for that specific point in time, after that, the tick does not reflect the current state of the system.

- You have to close open-nodes if they weren't ticked during a tick signal because if they weren't ticked, this means that the system configuration changed and these nodes aren't consistent anymore. For instance, suppose that you want to model the following situation:
  - you have a box on an random position;
  - if the user put the mouse over the box, don't do anything;
  - if the mouse is not over the box, wait 3 seconds and choose another random position
    - when the mouse enter the box, the timer must be reseted

  In this case, you would have to add a `Wait 3s` node (this means that once open, the node return SUCCESS only after the 3 seconds and RUNNING before that). But while it is open, the user put the mouse over the box and the `Wait` node must be reseted (which is accomplished by closing it).

**Comment by FunkMonkey** [comment]
HI @renatopp,

Thank you! This is really valuable input. I clearly did not think it through enough and saving the variables in the node was a stupid oversight - should have thought of that!.

I don't know if I should actually pursue this further in the near future instead of just going with @grifdail's idea for a promised leaf node - after all I should probably spend more time on my project itself than on the libraries I am using ;) guess I was over-engineering a little anyway.
But in case I try again some day and if (!) I actually come up with a better idea that satisfies these concerns, would you be willing to take another critical look at it? 

Again, thank you! :)

**Comment by renatopp** [comment]
Sure, @FunkMonkey =]
